---
version: "3.9"
services:
  web:
    image: docker.io/iancleary/ivy-lee-method:python3.11.1-slim
    env_file:
      - '_env/prod.env'
    ports:
      - "8000:8000"
    volumes:
      - './data:/data'
